nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: Catalogue de téléphones B2B. Authentification via JWT (Bearer).
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
